name: Check If Verification Works

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Unity - Activate
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        uses: game-ci/unity-activate@v2.0.0
        with:
          unity-version: 2019.4.28f1
          unity-serial: ${{ env.UNITY_LICENSE }}
          unity-username: ${{ env.UNITY_USERNAME }}
          unity-password: ${{ env.UNITY_PASSWORD }}
