name: CheckIfLicensed 🔐

on: workflow_dispatch

jobs:
  checkLicense:
    name: Check for the Unity license
    runs-on: ubuntu-latest
    env:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    steps:
      - name: Success! - Found a license
        if: ${{ startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 0
      - name: Fail - No License XX
        if: ${{ !startsWith(env.UNITY_LICENSE, '<') }}
        run: exit 1